comunidadeativa/urls.py
 



from django.urls import path

from comunidadeativa import views

app_name = 'amazoncred'

urlpatterns = [
     path('', views.index, name='index'),
     path('contato/', views.contato, name='contato'),
     path('perguntas-frequentes/', views.perguntas_frequentes, name='perguntas-frequentes'),
     path('programas/', views.programas, name='programas'),
     path('nossos-enderecos/', views.nossos_enderecos, name='nossos-enderecos'),
     path('noticias/', views.blog, name='blog'),
     path('noticias/post/novo' , views.post_novo, name='post_novo'),
     path('noticias/post/pesquisar/', views.pesquisar_post_htmx, name='pesquisar_post_htmx'),
     
     path('noticias/post/pesquisar/1/', views.pesquisar_post, name='pesquisar_post'),
     
     path('noticias/post/<slug:slug>' , views.post_detalhes, name='post-detalhes'),
     
     path('login' , views.login, name='login'),
     path('logout/', views.logout, name='logout'),

     path('transparencia/', views.transparencia, name='transparencia'),
     path('transparencia/tab/', views.tab, name='tab'),
     path('transparencia/novo_relatorio', views.novo_relatorio, name='novo_relatorio'),

     path('transparencia/editar_relatorio', views.editar_relatorio, name='editar_relatorio'),

     path('transparencia/remover_relatorio', views.remover_relatorio, name='remover_relatorio'),


     #path('blog/tags/<slug:slug>/', views.RecipeListViewTag.as_view(), name="tag"),


]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('comunidadeativa.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("select2/", include("django_select2.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comunidadeativa/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django_select2 import forms as s2forms
from django_select2.forms import Select2MultipleWidget, Select2Widget

from comunidadeativa.models import Categoria_Post, Contato, Relatorio, Tag

from .models import Post


# ModelSelect2MultipleWidget
# 
class TagWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "nome__icontains",
    ]

    queryset = Tag.objects.all()

    def value_from_datadict(self, data, files, name):
        
        values = list(set(super().value_from_datadict(data, files, name)))
        
        cleaned_values = []
        for value in values:
            if value.isnumeric():
                cleaned_values.append(value)
            else:
                obj,_ = Tag.objects.get_or_create(nome=value)
                cleaned_values.append(obj.id)
        
        
        return cleaned_values

class CategoriaWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "nome__icontains",
    ]

    queryset = Categoria_Post.objects.all()

    def value_from_datadict(self, data, files, name):
        
        values = list(set(super().value_from_datadict(data, files, name)))
        
        cleaned_values = []
        for categoria in values:
            if categoria.isnumeric():
                cleaned_values.append(categoria)
            else:
                obj,_ = Categoria_Post.objects.get_or_create(nome=categoria)
                cleaned_values.append(obj.id)
        
        
        return cleaned_values

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['titulo', 'conteudo', 'publicado', 'capa_post', 'categoria', 'tags']

        widgets = {
            'tags': TagWidget,
            'categoria': CategoriaWidget
        }


#Formulario de autenticação de usuários
class LoginForm(forms.Form):
    login = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Login', 'class':'form-control' }))
    
    senha = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget = forms.PasswordInput(attrs={'placeholder':'Senha', 'class':'form-control'})
    )

#TRANSPARENCIA
class RelatorioForm(forms.ModelForm):

    class Meta:
        model = Relatorio
        fields = ['titulo', 'arquivo', ]


#Fale Conosco | contato
class ContatoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["nome"].widget.attrs.update({"class": "form-control","placeholder": "Nome"})
        self.fields["email"].widget.attrs.update({"class": "form-control","placeholder": "email"})
        self.fields["assunto"].widget.attrs.update({"class": "form-control","placeholder": "assunto"})
        self.fields["mensagem"].widget.attrs.update({"class": "form-control","placeholder": "menssagem"})

    class Meta:
        model = Contato
        fields = ['nome', 'email', 'assunto', 'mensagem']
        
        widgets = {
            'tags': TagWidget,
            'categoria': CategoriaWidget
        }
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        regex = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
        
        if not re.fullmatch(regex, email):
            raise ValidationError("Endereço de e-mail inválido")
            
        return email

comunidadeativa/views.py
from datetime import datetime, timezone
from time import sleep

from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import ContatoForm, LoginForm, PostForm, RelatorioForm
from .models import Categoria_Post, Post, Relatorio, Tag
from .utils import utils


def index(request):
     posts_recentes = Post.objects.all().order_by('-id')[:3]
     return render(request, 'pages/index.html', {'posts': posts_recentes})

def contato(request):
     if request.method =='GET':
          form = ContatoForm()
          return render(request, 'pages/contato/contato.html', {'form': form})
     if request.method =='POST':
          template_name = 'pages/contato/partials/_contato-form.html'
          form = ContatoForm(request.POST)
          
          print('form is valid: ', form.is_valid() )
          if form.is_valid():
               form.save()
               form = ContatoForm()
               messages.success(request, 'Messagem enviada com sucesso')
               return render(request, template_name, {'form': form}) 
          
          return render(request, template_name, {'form': form})    

def perguntas_frequentes(request):
     return render(request, 'pages/perguntas-frequentes.html')

def programas(request):
     return render(request, 'pages/programas.html')


def nossos_enderecos(request):
     return render(request, 'pages/nossos-enderecos.html')

def blog(request):
     posts = Post.objects.all().order_by('-id')
     return render(request, 'pages/noticias/blog.html', {'posts': posts })

def post_detalhes(request, slug):
     if request.method == 'GET':
          post = Post.objects.get(slug=slug)
          postado_ha = utils.calcular_diferenca_datas(post.atualizado_em, datetime.now(timezone.utc))
          posts_recentes = Post.objects.exclude(id=post.id).order_by('-id')[:5]
          
          #Categorias
          
          categorias_posts = Categoria_Post.objects.all()
          categorias_e_qtd_post = []
          for categoria in categorias_posts:
               qtd_posts = categoria.post_set.count()
               if qtd_posts > 0:
                    categorias_e_qtd_post.append([categoria.nome, qtd_posts])
          
          categorias_e_qtd_post = sorted(categorias_e_qtd_post,key=lambda x: x[1],reverse= True)[:6]
          #TAGs
          tags = Tag.objects.all()[:12]

          contexto = {  
               'post': post, 
               'postado_ha': postado_ha, 
               'categorias_posts': categorias_e_qtd_post,
               'tags':tags,
               'posts_recentes': posts_recentes
               }
          return render(request, 'pages/noticias/blog-details.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def post_novo(request):
     if request.method == 'GET':
          form = PostForm()
          contexto = {  
                    'form': form
               }
          return render(request, 'pages/noticias/blog-details-edit.html', contexto)
     else:
          
          form = PostForm(request.POST, request.FILES)
          if form.is_valid():
               post = form.save(commit=False)
               post.autor = request.user
               post.save()
               form.save_m2m()
               messages.success(request, "Posto salvo com sucesso")
               return  redirect(reverse('amazoncred:blog'))
          
          return render(request, 'pages/noticias/blog-details-edit.html', {'form':form})
          
          

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def logout(request):
    auth.logout(request)
    print("Logout realizado com sucesso")
    return redirect(reverse('amazoncred:index'))

def login(request):

     if request.user.is_authenticated:
        return redirect(reverse('amazoncred:index'))

     if request.method == 'POST':
          form = LoginForm(request.POST)
          if form.is_valid():
               login = form['login'].value().lower().strip()
               senha = form['senha'].value()
               usuario = auth.authenticate(
                    request,
                    username=login,
                    password=senha
               )
               if usuario is not None:
                    auth.login(request, usuario)
                    next = request.GET.get("next", None)
                    if next is not None:
                         return redirect(next)
                    return redirect('amazoncred:login')

            
          messages.error(request, "Login ou Senha incorretos")
          return render(request, 'pages/login/login-page.html', {'form': form})
     else:
          parametro = request.GET.get('parametro')
          formLogin = LoginForm()
          contexto = {
               'form': formLogin
          }
     template_name = 'partials/login/_login_partial.html' if parametro else 'pages/login/login-page.html'
               
     return render(request, template_name, contexto)

def pesquisar_post_htmx(request):
     termo_pesquisado = request.POST.get('q', '').strip()
     print(termo_pesquisado)
     if not termo_pesquisado:
          return render(request, 'partials/noticias/_list_posts_search.html')

     posts = Post.objects.filter( 
                    Q(titulo__icontains = termo_pesquisado)
                    ).order_by('-id')[:11]
     return render(request, 'partials/noticias/_list_posts_search.html', {'posts': posts })

def pesquisar_post(request):
     termo_pesquisado = request.POST.get('q', '').strip()
     print(termo_pesquisado)
     if not termo_pesquisado:
          return render(request, 'partials/noticias/_list_posts_search.html')

     posts = Post.objects.filter( 
                    Q(titulo__icontains = termo_pesquisado)
                    ).order_by('-id')[:11]
     
     return render(request, 'pages/noticias/blog.html', {'posts': posts })


def transparencia(request):
     return render(request, 'pages/transparencia/transparencia.html')

def tab(request):
     tipo = request.GET.get('tipo')
     relatorios = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
     contexto = {   'obj_list': relatorios,
                    'tipo': tipo
               }

     return render(request, 'pages/transparencia/partials/_lista_relatorios.html', contexto)


@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def novo_relatorio(request):
     
     if request.method == "POST":
          id = request.POST.get('id')
          tipo = request.POST.get('tipo')
          
          if id:
               relatorio = get_object_or_404(Relatorio, pk = id)
               form = RelatorioForm(request.POST, request.FILES, instance=relatorio)
               if form.is_valid():
                    form.save()
                    
          else:
               form = RelatorioForm(request.POST, request.FILES)
          
               if form.is_valid():
                    relatorio = form.save(commit=False)
                    relatorio.tipo_relatorio = tipo.upper()
                    relatorio.save()
          
          demonstracoes_contabeis = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
          
          return render(request, 'pages/transparencia/partials/_lista_relatorios.html',{'obj_list': demonstracoes_contabeis})
     else:
          tipo = request.GET.get('tipo')
          form = RelatorioForm()
          contexto = {'form': form,
                      'tipo': tipo,
                      'novo': True,
                    'titulo':'Novo Relatório' }
          return render(request, 'pages/transparencia/partials/_novo_relatorio.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def editar_relatorio(request):
     
     id = request.GET.get('id')
     relatorio = get_object_or_404(Relatorio, pk = id)
     form = RelatorioForm(instance=relatorio)
     contexto = {'form': form,
                    'tipo': relatorio.tipo_relatorio,
                    'id': id,
                    'titulo':'Editar Relatório'}
     return render(request, 'pages/transparencia/partials/_novo_relatorio.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def remover_relatorio(request):
     
     id = request.POST.get('id')
     tipo = request.POST.get('tipo')

     print(id, tipo, '|\n' ,request.POST)
     
     relatorio = get_object_or_404(Relatorio, pk = id)
     relatorio.delete()
     
     demonstracoes_contabeis = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
     
     return render(request, 'pages/transparencia/partials/_lista_relatorios.html',{'obj_list': demonstracoes_contabeis})

"""
class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(
            slug=self.kwargs.get('slug', '')
        ).first()

        if not page_title:
            page_title = 'No recipes found'

        page_title = f'{page_title} - Tag |'

        ctx.update({
            'page_title': page_title,
        })

        return ctx

"""

comunidadeativa/templates/pages/noticias/blog-details-edit.html
{% extends "base.html"%}
{% load static %}
{% load widget_tweaks %}
{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="page-header d-flex align-items-center" style="background-image: url('');">
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Blog Details</h2>
              <p>Odio et unde deleniti. Deserunt numquam exercitationem. Officiis quo odio sint voluptas consequatur ut a odio voluptatem. Sit dolorum debitis veritatis natus dolores. Quasi ratione sint. Sit quaerat ipsum dolorem.</p>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="{% url 'amazoncred:index' %}">Home</a></li>
            <li><a href="{% url 'amazoncred:blog' %}">Blog</a></li>
            <li>Post Details</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Blog Details Section ======= -->
    
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row g-5">

          <div class="col-lg-8">

            <article class="blog-details">

              <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                {{ form.media }}
                {% for field in form.visible_fields %}

                <div class="form-group mt-3 mb-3 d-flex row">
                    <div class="label-class text-start">
                        <label class="col-form-label " for="{{ field.id_for_label}}">
                            {{field.label}}</label>
                    </div>
                    <div class="d-inline-flex flex-row">
                        
                        {% if field.name == 'publicado' %}
                          {{field|add_class:'form-check-input'}}
                        {% else %}
                          {{field|add_class:'form-control'}}
                        {% endif %}
                        

                        {% if field.errors %}
                        <span style="color: red;" role="alert">
                            {{field.errors}}   
                        </span>
                        {% endif %}
                    </div>
                    <small class="form-text text-muted d-flex justify-content-center">{{ field.help_text }}</small>
                </div>
                {% endfor %}
                

                <button type="submit">Enviar</button>
              </form>
   
            </article><!-- End blog post -->

          </div>

        </div>
      </div>
    </section><!-- End Blog Details Section -->
  </main><!-- End #main -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  {{ form.media.js }}
  {% endblock %}

comunidadeativa/templates/pages/noticias/blog-details.html
{% extends "base.html"%}
{% load static %}
{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <nav>
        <div class="container">
          <ol>
            <li><a href="{% url 'amazoncred:index' %}">Home</a></li>
            <li><a href="{% url 'amazoncred:blog' %}">Blog</a></li>
            <li>Post Details</li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Blog Details Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">
        {% include 'partials/_alertas.html' %}
        <div class="row g-5">

          <div class="col-lg-8">

            <article id='post-details' class="blog-details">
              {% load static %}
              <div class="post-img">
                  {% if post.capa_post  %}
                    <img src="{{ post.capa_post.url }}" alt="" class="img-fluid"> 
                    {% else %}
                    <img src="{% static 'assets/img/blog/blog-1.jpg' %}" alt="" class="img-fluid" >
                  {% endif %}
                </div>
              
                <h2 class="title">{{ post.titulo }}</h2>
              
                <div class="meta-top">
                  <ul>
                    <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-details.html">{{post.autor}}</a></li>
                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-details.html"><time>{{post.criado_em|date:'d M, Y'}}, {{postado_ha}}</time></a></li>
                  </ul>
                </div><!-- End meta top -->
              
                <div class="content">
                  {{ post.conteudo|safe }}
              
                </div><!-- End post content -->
              
                <div class="meta-bottom">
                  <i class="bi bi-folder"></i>
                  <ul class="cats">
                    <li><a href="#">{{ post.categoria }}</a></li>
                  </ul>
              
                  <i class="bi bi-tags"></i>
                  <ul class="tags">
                    {% for tag in post.tags.all %}
                      <li><a href="#">{{tag}}</a></li>
                    {% endfor %}
                  </ul>
                </div><!-- End meta bottom -->
            </article><!-- End blog post -->


          </div>

          <div class="col-lg-4">

            <div class="sidebar">

              <div class="sidebar-item search-form">
                <h3 class="sidebar-title">Pesquisar</h3>
                <form action="{% url 'amazoncred:pesquisar_post' %}" method="post" class="mt-3">
                  {% csrf_token %}
                  <input type="text" name='q'
                    hx-post="{% url 'amazoncred:pesquisar_post_htmx' %}" 
                    hx-trigger="keyup changed delay:500ms, search" 
                    hx-target="#result-search" 
                    hx-indicator=".htmx-indicator"
                    hx-swap="innerHTML">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
                <div class="result-search" id="result-search">

                </div>
              </div><!-- End sidebar search formn-->

              <div class="sidebar-item categories">
                <h3 class="sidebar-title">Categories</h3>
                <ul class="mt-3">
                 
                 {% for categoria_post, numero in categorias_posts  %}
                  <li>
                    <a href="#">{{categoria_post|title}} <span>({{numero}})</span></a>
                  </li>
                  {% empty %}
                  <li>Sem categorias</li>

                 {% endfor %}
                </ul>
              </div><!-- End sidebar categories-->

              <div class="sidebar-item recent-posts">
                <h3 class="sidebar-title">Posts recentes</h3>
                
                <div class="mt-3">
                {% for post_recente in posts_recentes %}
                
                    <div class="post-item mt-3 pb-3">
                      {% if post_recente.capa_post  %}
                        <img src="{{ post_recente.capa_post.url }}" alt="" class="img-fluid"> 
                      {% else %}
                        <img src="{% static 'assets/img/blog/blog-1.jpg' %}" alt="" class="img-fluid" >
                      {% endif %}
                      <div>
                        <h4><a href="{% url 'amazoncred:post-detalhes' post_recente.slug %}">{{ post_recente.titulo }}</a></h4>
                        <time>{{ post_recente.criado_em }}</time>
                      </div>
                    </div>
                    {% endfor %}
                </div>


              </div><!-- End sidebar recent posts-->

              <div class="sidebar-item tags">
                <h3 class="sidebar-title">Tags</h3>
                <ul class="mt-3">
                  {% for tag in tags  %}
                  <li><a href="#">{{ tag }}</a></li>
                  {% empty %}
                  <li><a href="#">Sem Tas</a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar tags-->

            </div><!-- End Blog Sidebar -->

          </div>
        </div>

      </div>
    </section><!-- End Blog Details Section -->

  </main><!-- End #main -->

  {% endblock content %}

comunidadeativa/templates/pages/noticias/blog.html
{% extends "base.html"%}
{% load static %}
{% block content %}

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="cover page-header d-flex align-items-center" >
        <div class="container position-relative">
          <div class="row d-flex justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Notícias sobre a ComunidadeAtiva</h2>
              <p>Fique por dentro</p>
            </div>
          </div>
        </div>
      </div>
      <nav>
        <div class="container">
          <ol>
            <li><a href="{% url 'amazoncred:index' %}">Home</a></li>
            <li><a href="{% url 'amazoncred:blog' %}">Blog</a></li>
          </ol>
        </div>
      </nav>
    </div><!-- End Breadcrumbs -->
    
    
    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">
        
        {% include 'partials/_alertas.html' %}

        <div class="d-flex justify-content-between">

          <div class="search-form col-8">
            <h3 class="search-form-title">Pesquisar</h3>
          {% comment %} action="{% url 'amazoncred:pesquisar_post' %}" {% endcomment %}
            <form action="{% url 'amazoncred:pesquisar_post' %}" method="post" class="mt-3"> {% csrf_token %}
              <input class="search-input" type="text" name='q' value= {{request.POST.q}}
              hx-post="{% url 'amazoncred:pesquisar_post_htmx' %}" 
              hx-trigger="keyup changed delay:500ms, search" 
              hx-target="#result-search" 
              hx-swap="innerHTML">
              <button type="submit"> <i class="bi bi-search"></i>
              </button>
            </form>

            <div class="result-search" id="result-search">
    
            </div>
          </div>
      
          {% if user.is_authenticated %}
          <div class="align-self-end mt-1">
            <a href="{% url 'amazoncred:post_novo' %}">  
              <button type="submit" class="btn btn-success"> Novo Post</button>
            </a>
          </div>
          {% endif %}
        </div>
      
        <div class="row gy-4 posts-list mt-1">
          <div hx-after="teste()" id="list_posts" >
            {% include 'partials/noticias/_list_posts.html' %}
          </div> 
        </div><!-- End blog posts list -->

        <div class="blog-pagination">
          <ul class="justify-content-center">
            <li><a href="#">1</a></li>
            <li class="active"><a href="#">2</a></li>
            <li><a href="#">3</a></li>
          </ul>
        </div><!-- End blog pagination -->

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  {% endblock content %}