comunidadeativa/urls.py
 



from django.urls import path

from comunidadeativa import views

app_name = 'amazoncred'

urlpatterns = [
     path('', views.index, name='index'),
     path('contato/', views.contato, name='contato'),
     path('perguntas-frequentes/', views.perguntas_frequentes, name='perguntas-frequentes'),
     path('programas/', views.programas, name='programas'),
     path('nossos-enderecos/', views.nossos_enderecos, name='nossos-enderecos'),
     path('noticias/', views.blog, name='blog'),
     path('noticias/post/novo' , views.post_novo, name='post_novo'),
     path('noticias/post/pesquisar/', views.pesquisar_post_htmx, name='pesquisar_post_htmx'),
     
     path('noticias/post/pesquisar/1/', views.pesquisar_post, name='pesquisar_post'),
     
     path('noticias/post/<slug:slug>' , views.post_detalhes, name='post-detalhes'),
     
     path('login' , views.login, name='login'),
     path('logout/', views.logout, name='logout'),

     path('transparencia/', views.transparencia, name='transparencia'),
     path('transparencia/tab/', views.tab, name='tab'),
     path('transparencia/novo_relatorio', views.novo_relatorio, name='novo_relatorio'),

     path('transparencia/editar_relatorio', views.editar_relatorio, name='editar_relatorio'),

     path('transparencia/remover_relatorio', views.remover_relatorio, name='remover_relatorio'),


     #path('blog/tags/<slug:slug>/', views.RecipeListViewTag.as_view(), name="tag"),


]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('comunidadeativa.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("select2/", include("django_select2.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comunidadeativa/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django_select2 import forms as s2forms
from django_select2.forms import Select2MultipleWidget, Select2Widget

from comunidadeativa.models import Categoria_Post, Contato, Relatorio, Tag

from .models import Post


# ModelSelect2MultipleWidget
# 
class TagWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "nome__icontains",
    ]

    queryset = Tag.objects.all()

    def value_from_datadict(self, data, files, name):
        
        values = list(set(super().value_from_datadict(data, files, name)))
        
        cleaned_values = []
        for value in values:
            if value.isnumeric():
                cleaned_values.append(value)
            else:
                obj,_ = Tag.objects.get_or_create(nome=value)
                cleaned_values.append(obj.id)
        
        
        return cleaned_values

class CategoriaWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "nome__icontains",
    ]

    queryset = Categoria_Post.objects.all()

    def value_from_datadict(self, data, files, name):
        
        values = list(set(super().value_from_datadict(data, files, name)))
        
        cleaned_values = []
        for categoria in values:
            if categoria.isnumeric():
                cleaned_values.append(categoria)
            else:
                obj,_ = Categoria_Post.objects.get_or_create(nome=categoria)
                cleaned_values.append(obj.id)
        
        
        return cleaned_values

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['titulo', 'conteudo', 'publicado', 'capa_post', 'categoria', 'tags']

        widgets = {
            'tags': TagWidget,
            'categoria': CategoriaWidget
        }


#Formulario de autenticação de usuários
class LoginForm(forms.Form):
    login = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Login', 'class':'form-control' }))
    
    senha = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget = forms.PasswordInput(attrs={'placeholder':'Senha', 'class':'form-control'})
    )

#TRANSPARENCIA
class RelatorioForm(forms.ModelForm):

    class Meta:
        model = Relatorio
        fields = ['titulo', 'arquivo', ]


#Fale Conosco | contato
class ContatoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["nome"].widget.attrs.update({"class": "form-control","placeholder": "Nome"})
        self.fields["email"].widget.attrs.update({"class": "form-control","placeholder": "email"})
        self.fields["assunto"].widget.attrs.update({"class": "form-control","placeholder": "assunto"})
        self.fields["mensagem"].widget.attrs.update({"class": "form-control","placeholder": "menssagem"})

    class Meta:
        model = Contato
        fields = ['nome', 'email', 'assunto', 'mensagem']
        
        widgets = {
            'tags': TagWidget,
            'categoria': CategoriaWidget
        }
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        regex = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
        
        if not re.fullmatch(regex, email):
            raise ValidationError("Endereço de e-mail inválido")
            
        return email

comunidadeativa/views.py
from datetime import datetime, timezone
from time import sleep

from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import ContatoForm, LoginForm, PostForm, RelatorioForm
from .models import Categoria_Post, Post, Relatorio, Tag
from .utils import utils


def index(request):
     posts_recentes = Post.objects.all().order_by('-id')[:3]
     return render(request, 'pages/index.html', {'posts': posts_recentes})

def contato(request):
     if request.method =='GET':
          form = ContatoForm()
          return render(request, 'pages/contato/contato.html', {'form': form})
     if request.method =='POST':
          template_name = 'pages/contato/partials/_contato-form.html'
          form = ContatoForm(request.POST)
          
          print('form is valid: ', form.is_valid() )
          if form.is_valid():
               form.save()
               form = ContatoForm()
               messages.success(request, 'Messagem enviada com sucesso')
               return render(request, template_name, {'form': form}) 
          
          return render(request, template_name, {'form': form})    

def perguntas_frequentes(request):
     return render(request, 'pages/perguntas-frequentes.html')

def programas(request):
     return render(request, 'pages/programas.html')


def nossos_enderecos(request):
     return render(request, 'pages/nossos-enderecos.html')

def blog(request):
     posts = Post.objects.all().order_by('-id')
     return render(request, 'pages/noticias/blog.html', {'posts': posts })

def post_detalhes(request, slug):
     if request.method == 'GET':
          post = Post.objects.get(slug=slug)
          postado_ha = utils.calcular_diferenca_datas(post.atualizado_em, datetime.now(timezone.utc))
          posts_recentes = Post.objects.exclude(id=post.id).order_by('-id')[:5]
          
          #Categorias
          
          categorias_posts = Categoria_Post.objects.all()
          categorias_e_qtd_post = []
          for categoria in categorias_posts:
               qtd_posts = categoria.post_set.count()
               if qtd_posts > 0:
                    categorias_e_qtd_post.append([categoria.nome, qtd_posts])
          
          categorias_e_qtd_post = sorted(categorias_e_qtd_post,key=lambda x: x[1],reverse= True)[:6]
          #TAGs
          tags = Tag.objects.all()[:12]

          contexto = {  
               'post': post, 
               'postado_ha': postado_ha, 
               'categorias_posts': categorias_e_qtd_post,
               'tags':tags,
               'posts_recentes': posts_recentes
               }
          return render(request, 'pages/noticias/blog-details.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def post_novo(request):
     if request.method == 'GET':
          form = PostForm()
          contexto = {  
                    'form': form
               }
          return render(request, 'pages/noticias/blog-details-edit.html', contexto)
     else:
          
          form = PostForm(request.POST, request.FILES)
          if form.is_valid():
               post = form.save(commit=False)
               post.autor = request.user
               post.save()
               form.save_m2m()
               messages.success(request, "Posto salvo com sucesso")
               return  redirect(reverse('amazoncred:blog'))
          
          return render(request, 'pages/noticias/blog-details-edit.html', {'form':form})
          
          

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def logout(request):
    auth.logout(request)
    print("Logout realizado com sucesso")
    return redirect(reverse('amazoncred:index'))

def login(request):

     if request.user.is_authenticated:
        return redirect(reverse('amazoncred:index'))

     if request.method == 'POST':
          form = LoginForm(request.POST)
          if form.is_valid():
               login = form['login'].value().lower().strip()
               senha = form['senha'].value()
               usuario = auth.authenticate(
                    request,
                    username=login,
                    password=senha
               )
               if usuario is not None:
                    auth.login(request, usuario)
                    next = request.GET.get("next", None)
                    if next is not None:
                         return redirect(next)
                    return redirect('amazoncred:login')

            
          messages.error(request, "Login ou Senha incorretos")
          return render(request, 'pages/login/login-page.html', {'form': form})
     else:
          parametro = request.GET.get('parametro')
          formLogin = LoginForm()
          contexto = {
               'form': formLogin
          }
     template_name = 'partials/login/_login_partial.html' if parametro else 'pages/login/login-page.html'
               
     return render(request, template_name, contexto)

def pesquisar_post_htmx(request):
     termo_pesquisado = request.POST.get('q', '').strip()
     print(termo_pesquisado)
     if not termo_pesquisado:
          return render(request, 'partials/noticias/_list_posts_search.html')

     posts = Post.objects.filter( 
                    Q(titulo__icontains = termo_pesquisado)
                    ).order_by('-id')[:11]
     return render(request, 'partials/noticias/_list_posts_search.html', {'posts': posts })

def pesquisar_post(request):
     termo_pesquisado = request.POST.get('q', '').strip()
     print(termo_pesquisado)
     if not termo_pesquisado:
          return render(request, 'partials/noticias/_list_posts_search.html')

     posts = Post.objects.filter( 
                    Q(titulo__icontains = termo_pesquisado)
                    ).order_by('-id')[:11]
     
     return render(request, 'pages/noticias/blog.html', {'posts': posts })


def transparencia(request):
     return render(request, 'pages/transparencia/transparencia.html')

def tab(request):
     tipo = request.GET.get('tipo')
     relatorios = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
     contexto = {   'obj_list': relatorios,
                    'tipo': tipo
               }

     return render(request, 'pages/transparencia/partials/_lista_relatorios.html', contexto)


@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def novo_relatorio(request):
     
     if request.method == "POST":
          id = request.POST.get('id')
          tipo = request.POST.get('tipo')
          
          if id:
               relatorio = get_object_or_404(Relatorio, pk = id)
               form = RelatorioForm(request.POST, request.FILES, instance=relatorio)
               if form.is_valid():
                    form.save()
                    
          else:
               form = RelatorioForm(request.POST, request.FILES)
          
               if form.is_valid():
                    relatorio = form.save(commit=False)
                    relatorio.tipo_relatorio = tipo.upper()
                    relatorio.save()
          
          demonstracoes_contabeis = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
          
          return render(request, 'pages/transparencia/partials/_lista_relatorios.html',{'obj_list': demonstracoes_contabeis})
     else:
          tipo = request.GET.get('tipo')
          form = RelatorioForm()
          contexto = {'form': form,
                      'tipo': tipo,
                      'novo': True,
                    'titulo':'Novo Relatório' }
          return render(request, 'pages/transparencia/partials/_novo_relatorio.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def editar_relatorio(request):
     
     id = request.GET.get('id')
     relatorio = get_object_or_404(Relatorio, pk = id)
     form = RelatorioForm(instance=relatorio)
     contexto = {'form': form,
                    'tipo': relatorio.tipo_relatorio,
                    'id': id,
                    'titulo':'Editar Relatório'}
     return render(request, 'pages/transparencia/partials/_novo_relatorio.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def remover_relatorio(request):
     
     id = request.POST.get('id')
     tipo = request.POST.get('tipo')

     print(id, tipo, '|\n' ,request.POST)
     
     relatorio = get_object_or_404(Relatorio, pk = id)
     relatorio.delete()
     
     demonstracoes_contabeis = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
     
     return render(request, 'pages/transparencia/partials/_lista_relatorios.html',{'obj_list': demonstracoes_contabeis})

"""
class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(
            slug=self.kwargs.get('slug', '')
        ).first()

        if not page_title:
            page_title = 'No recipes found'

        page_title = f'{page_title} - Tag |'

        ctx.update({
            'page_title': page_title,
        })

        return ctx

"""

comunidadeativa/templates/partials/_alertas.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        <p> {{ message }}</p>
    </div>
    {% endfor %}
{% endif %}

comunidadeativa/templates/partials/_call_to_action.html
    <!-- ======= Call To Action Section ======= -->
    <section id="call-to-action" class="call-to-action">
        <div class="container text-center" data-aos="zoom-out">
          <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox play-btn"></a>
          <h3>Call To Action</h3>
          <p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <a class="cta-btn" href="#">Call To Action</a>
        </div>
      </section><!-- End Call To Action Section -->

comunidadeativa/templates/partials/_clientes.html
{% load static %}
<!-- ======= Clients Section ======= -->
<section id="clients" class="clients">
    <div class="container" data-aos="zoom-out">
      <div class="section-header">
        <h2>Nossos Parceiros</h2>
        <p></p>
      </div>

      <div class="clients-slider swiper">
        <div class="swiper-wrapper align-items-center">
          <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-1.png' %}" class="img-fluid" alt=""></div>
          <div class="swiper-slide"><img src="{% static 'assets/img/clients/client-2.png' %}" class="img-fluid" alt=""></div>
        </div>
      </div>

    </div>
  </section><!-- End Clients Section -->

comunidadeativa/templates/partials/_estatisticas.html
 {% load static %}
 <!-- ======= Stats Counter Section ======= -->
 <section id="stats-counter" class="stats-counter">
    <div class="container" data-aos="fade-up">

      <div class="row gy-4 align-items-center">

        <div class="col-lg-6">
          <img src="{% static 'assets/img/stats-img.svg' %}" alt="" class="img-fluid">
        </div>

        <div class="col-lg-6">

          <div class="stats-item d-flex align-items-center">
            <span data-purecounter-start="0" data-purecounter-end="232" data-purecounter-duration="1" class="purecounter"></span>
            <p><strong>Happy Clients</strong> consequuntur quae diredo para mesta</p>
          </div><!-- End Stats Item -->

          <div class="stats-item d-flex align-items-center">
            <span data-purecounter-start="0" data-purecounter-end="521" data-purecounter-duration="1" class="purecounter"></span>
            <p><strong>Projects</strong> adipisci atque cum quia aut</p>
          </div><!-- End Stats Item -->

          <div class="stats-item d-flex align-items-center">
            <span data-purecounter-start="0" data-purecounter-end="453" data-purecounter-duration="1" class="purecounter"></span>
            <p><strong>Hours Of Support</strong> aut commodi quaerat</p>
          </div><!-- End Stats Item -->

        </div>

      </div>

    </div>
  </section><!-- End Stats Counter Section -->

comunidadeativa/templates/partials/_footer.html
  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-4">
        <div class="col-lg-5 col-md-12 footer-info">
          <a href="index.html" class="logo d-flex align-items-center">
            <span>Comunidade Ativa</span>
          </a>
          <!-- <p>O desenvolvimento começa no pequeno.</p>-->
          <p>O maior e melhor microcrédito da Amazônia.</p>
          <div class="social-links d-flex mt-4">
            <a href="{{redes_sociais.twitter}}" target="_blank" class="twitter"><i class="bi bi-twitter"></i></a>
            
            <a href="{{redes_sociais.facebook}}" target="_blank" class="facebook"><i class="bi bi-facebook"></i></a>
            
            <a href="{{redes_sociais.instagram}}" target="_blank" class="instagram"><i class="bi bi-instagram"></i></a>
            
            <a href="{{redes_sociais.linkedin}}" target="_blank" class="linkedin"><i class="bi bi-linkedin"></i></a>
          
          </div>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Useful Links</h4>
          <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Terms of service</a></li>
            <li><a href="#">Privacy policy</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-6 footer-links">
          <h4>Our Services</h4>
          <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Web Development</a></li>
            <li><a href="#">Product Management</a></li>
            <li><a href="#">Marketing</a></li>
            <li><a href="#">Graphic Design</a></li>
          </ul>
        </div>

        <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
          <h4>Contact Us</h4>
          <p>
            A108 Adam Street <br>
            New York, NY 535022<br>
            United States <br><br>
            <strong>Phone:</strong> +1 5589 55488 55<br>
            <strong>Email:</strong> info@example.com<br>
          </p>

        </div>

      </div>
    </div>

    <div class="container mt-4">
      <div class="copyright">
      </div>
    </div>

  </footer><!-- End Footer -->
  <!-- End Footer -->

comunidadeativa/templates/partials/_header.html
  <!-- ======= Header ======= -->
  <section id="topbar" class="topbar d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-end">

      <div class="contact-info d-flex align-items-center" >
        <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">{{contato.email}}</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>{{contato.telefone}}</span></i>
        
      </div>

      <div class="social-links d-none d-md-flex align-items-center">

        <a href="{{redes_sociais.twitter}}" target="_blank" class="twitter"><i class="bi bi-twitter"></i></a>
            
        <a href="{{redes_sociais.facebook}}" target="_blank" class="facebook"><i class="bi bi-facebook"></i></a>
        
        <a href="{{redes_sociais.instagram}}" target="_blank" class="instagram"><i class="bi bi-instagram"></i></a>
        
        <a href="{{redes_sociais.linkedin}}" target="_blank" class="linkedin"><i class="bi bi-linkedin"></i></a>

      </div>
    </div>
  </section><!-- End Top Bar -->

  <header id="header" class="header d-flex align-items-center">

    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">
      <a href="{% url 'amazoncred:index' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>Comunidade<span class="titulo-logomarca">Ativa</span></h1>
      </a>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'amazoncred:index' %}">Início</a></li>
          <li><a href="#about">Sobre</a></li>
          
          <li class="dropdown"><a href="{% url 'amazoncred:programas' %}"><span>Programas</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
                <li><a href="#">Comunidade Ativa Rural</a></li>
                <li><a href="#">Comunidade Ativa Urbano</a></li>
                <li><a href="#team">Aprendiz de Aprendizes</a></li>
            </ul>
          </li>


          <li><a href="{% url 'amazoncred:transparencia' %}">Transparência</a></li>
          <li><a href="{% url 'amazoncred:blog' %}">Notícias</a></li>
          <li><a href="{% url 'amazoncred:nossos-enderecos' %}">Nossos Endereços</a></li>
          <li class="dropdown"><a href="#teste"><span>Fale Conosco</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
                <li><a href="{% url 'amazoncred:contato' %}">Contato</a></li>
                <li><a href="#team">Trabalhe Conosco</a></li>
                <li><a href="{% url 'amazoncred:perguntas-frequentes' %}">Perguntas Frequentes</a></li>
            </ul>
          </li>


          {% if user.is_authenticated %}
          <li class="dropdown"><a href="#"><span> {{ user.get_username |title }}</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
                <li><a href="#">Meus Dados</a></li>
                <li><a href="{% url 'amazoncred:logout' %}">Sair</a></li>
            </ul>
          </li>
          {% else %}
            <li><a href="" data-bs-toggle="modal"                           data-bs-target="#login-modal"
              hx-get="{% url 'amazoncred:login' %}?parametro=True"
              hx-trigger="click"
              hx-target="#login-modal-content"
              >
              Entrar 
              
              <div class="htmx-indicator" >
                <i class="fa-solid fa-spinner fa-spin-pulse"></i>
              </div> 
            </a></li>
            
            <!-- Modal Login -->
            <div class="modal fade" id="login-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div id="login-modal-content" class="modal-body">
                    {% include 'partials/login/_login_partial.html' %}
                  </div>
                </div>
              </div>
            </div>

            
            
          {% endif %}

          
          
        </ul>
      </nav><!-- .navbar -->

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header><!-- End Header -->

comunidadeativa/templates/partials/_sobre-nos.html
{% load static %}
<!-- ======= About Us Section ======= -->
<section id="about" class="about">
    <div class="container" data-aos="fade-up">

      <div class="section-header">
        <h2>Sobre Nós</h2>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi suscipit ipsa repellat ullam molestiae eaque quisquam, ut reiciendis a harum, obcaecati ducimus accusamus quas aperiam voluptatem doloremque veniam, neque vel.</p>
      </div>

      <div class="row gy-4">
        <div class="col-lg-6">
          {% comment %} <h3> Seja Bem-vindo </h3> {% endcomment %}
          <img src="{% static 'assets/img/sobre.png' %}" class="img-fluid rounded-4 mb-4" alt="">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, voluptatibus, maxime placeat provident autem nostrum temporibus, ullam impedit nisi ut laboriosam est natus. In sed officiis sequi temporibus doloribus aperiam.</p>
          
        </div>

        <div class="col-lg-6">
          <div class="content ps-0 ps-lg-5">
            <p class="fst-italic"> A Comunidade Ativa tem como missão "promover o desenvolvimento sustentável com equidade social e econômica para os empreendedores populares da região da Amazônia legal".</p>
            </p>
{% comment %}             <ul>
              <li><i class="bi bi-check-circle-fill"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
              <li><i class="bi bi-check-circle-fill"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
              <li><i class="bi bi-check-circle-fill"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
            </ul> {% endcomment %}
            
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos amet facilis debitis nemo hic est molestiae, ipsa laudantium incidunt tempore suscipit necessitatibus quis, omnis nobis. Provident molestiae quaerat vitae sequi!</p>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro consequuntur rem cum illum quaerat fuga, velit ut dolore, praesentium consequatur ullam quod officiis iure non libero veritatis adipisci suscipit provident. 

            </p>

            <div class="position-relative mt-4">
              <img src="{% static 'assets/img/about-2.jpg' %}" class="img-fluid rounded-4" alt="">
              <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ" class="glightbox play-btn"></a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section><!-- End About Us Section -->