comunidadeativa/urls.py
 



from django.urls import path

from comunidadeativa import views

app_name = 'amazoncred'

urlpatterns = [
     path('', views.index, name='index'),
     path('contato/', views.contato, name='contato'),
     path('perguntas-frequentes/', views.perguntas_frequentes, name='perguntas-frequentes'),
     path('programas/', views.programas, name='programas'),
     path('nossos-enderecos/', views.nossos_enderecos, name='nossos-enderecos'),
     path('noticias/', views.blog, name='blog'),
     path('noticias/post/novo' , views.post_novo, name='post_novo'),
     path('noticias/post/pesquisar/', views.pesquisar_post_htmx, name='pesquisar_post_htmx'),
     
     path('noticias/post/pesquisar/1/', views.pesquisar_post, name='pesquisar_post'),
     
     path('noticias/post/<slug:slug>' , views.post_detalhes, name='post-detalhes'),
     
     path('login' , views.login, name='login'),
     path('logout/', views.logout, name='logout'),

     path('transparencia/', views.transparencia, name='transparencia'),
     path('transparencia/tab/', views.tab, name='tab'),
     path('transparencia/novo_relatorio', views.novo_relatorio, name='novo_relatorio'),

     path('transparencia/editar_relatorio', views.editar_relatorio, name='editar_relatorio'),

     path('transparencia/remover_relatorio', views.remover_relatorio, name='remover_relatorio'),


     #path('blog/tags/<slug:slug>/', views.RecipeListViewTag.as_view(), name="tag"),


]

setup/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('comunidadeativa.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("select2/", include("django_select2.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comunidadeativa/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django_select2 import forms as s2forms
from django_select2.forms import Select2MultipleWidget, Select2Widget

from comunidadeativa.models import Categoria_Post, Contato, Relatorio, Tag

from .models import Post


# ModelSelect2MultipleWidget
# 
class TagWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "nome__icontains",
    ]

    queryset = Tag.objects.all()

    def value_from_datadict(self, data, files, name):
        
        values = list(set(super().value_from_datadict(data, files, name)))
        
        cleaned_values = []
        for value in values:
            if value.isnumeric():
                cleaned_values.append(value)
            else:
                obj,_ = Tag.objects.get_or_create(nome=value)
                cleaned_values.append(obj.id)
        
        
        return cleaned_values

class CategoriaWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "nome__icontains",
    ]

    queryset = Categoria_Post.objects.all()

    def value_from_datadict(self, data, files, name):
        
        values = list(set(super().value_from_datadict(data, files, name)))
        
        cleaned_values = []
        for categoria in values:
            if categoria.isnumeric():
                cleaned_values.append(categoria)
            else:
                obj,_ = Categoria_Post.objects.get_or_create(nome=categoria)
                cleaned_values.append(obj.id)
        
        
        return cleaned_values

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['titulo', 'conteudo', 'publicado', 'capa_post', 'categoria', 'tags']

        widgets = {
            'tags': TagWidget,
            'categoria': CategoriaWidget
        }


#Formulario de autenticação de usuários
class LoginForm(forms.Form):
    login = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget= forms.TextInput(attrs={'placeholder':'Login', 'class':'form-control' }))
    
    senha = forms.CharField(
        label=False,
        max_length=100,
        required=True,
        widget = forms.PasswordInput(attrs={'placeholder':'Senha', 'class':'form-control'})
    )

#TRANSPARENCIA
class RelatorioForm(forms.ModelForm):

    class Meta:
        model = Relatorio
        fields = ['titulo', 'arquivo', ]


#Fale Conosco | contato
class ContatoForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["nome"].widget.attrs.update({"class": "form-control","placeholder": "Nome"})
        self.fields["email"].widget.attrs.update({"class": "form-control","placeholder": "email"})
        self.fields["assunto"].widget.attrs.update({"class": "form-control","placeholder": "assunto"})
        self.fields["mensagem"].widget.attrs.update({"class": "form-control","placeholder": "menssagem"})

    class Meta:
        model = Contato
        fields = ['nome', 'email', 'assunto', 'mensagem']
        
        widgets = {
            'tags': TagWidget,
            'categoria': CategoriaWidget
        }
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        regex = re.compile(r'([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\.[A-Z|a-z]{2,})+')
        
        if not re.fullmatch(regex, email):
            raise ValidationError("Endereço de e-mail inválido")
            
        return email

comunidadeativa/views.py
from datetime import datetime, timezone
from time import sleep

from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import ContatoForm, LoginForm, PostForm, RelatorioForm
from .models import Categoria_Post, Post, Relatorio, Tag
from .utils import utils


def index(request):
     posts_recentes = Post.objects.all().order_by('-id')[:3]
     return render(request, 'pages/index.html', {'posts': posts_recentes})

def contato(request):
     if request.method =='GET':
          form = ContatoForm()
          return render(request, 'pages/contato/contato.html', {'form': form})
     if request.method =='POST':
          template_name = 'pages/contato/partials/_contato-form.html'
          form = ContatoForm(request.POST)
          
          print('form is valid: ', form.is_valid() )
          if form.is_valid():
               form.save()
               form = ContatoForm()
               messages.success(request, 'Messagem enviada com sucesso')
               return render(request, template_name, {'form': form}) 
          
          return render(request, template_name, {'form': form})    

def perguntas_frequentes(request):
     return render(request, 'pages/perguntas-frequentes.html')

def programas(request):
     return render(request, 'pages/programas.html')


def nossos_enderecos(request):
     return render(request, 'pages/nossos-enderecos.html')

def blog(request):
     posts = Post.objects.all().order_by('-id')
     return render(request, 'pages/noticias/blog.html', {'posts': posts })

def post_detalhes(request, slug):
     if request.method == 'GET':
          post = Post.objects.get(slug=slug)
          postado_ha = utils.calcular_diferenca_datas(post.atualizado_em, datetime.now(timezone.utc))
          posts_recentes = Post.objects.exclude(id=post.id).order_by('-id')[:5]
          
          #Categorias
          
          categorias_posts = Categoria_Post.objects.all()
          categorias_e_qtd_post = []
          for categoria in categorias_posts:
               qtd_posts = categoria.post_set.count()
               if qtd_posts > 0:
                    categorias_e_qtd_post.append([categoria.nome, qtd_posts])
          
          categorias_e_qtd_post = sorted(categorias_e_qtd_post,key=lambda x: x[1],reverse= True)[:6]
          #TAGs
          tags = Tag.objects.all()[:12]

          contexto = {  
               'post': post, 
               'postado_ha': postado_ha, 
               'categorias_posts': categorias_e_qtd_post,
               'tags':tags,
               'posts_recentes': posts_recentes
               }
          return render(request, 'pages/noticias/blog-details.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def post_novo(request):
     if request.method == 'GET':
          form = PostForm()
          contexto = {  
                    'form': form
               }
          return render(request, 'pages/noticias/blog-details-edit.html', contexto)
     else:
          
          form = PostForm(request.POST, request.FILES)
          if form.is_valid():
               post = form.save(commit=False)
               post.autor = request.user
               post.save()
               form.save_m2m()
               messages.success(request, "Posto salvo com sucesso")
               return  redirect(reverse('amazoncred:blog'))
          
          return render(request, 'pages/noticias/blog-details-edit.html', {'form':form})
          
          

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def logout(request):
    auth.logout(request)
    print("Logout realizado com sucesso")
    return redirect(reverse('amazoncred:index'))

def login(request):

     if request.user.is_authenticated:
        return redirect(reverse('amazoncred:index'))

     if request.method == 'POST':
          form = LoginForm(request.POST)
          if form.is_valid():
               login = form['login'].value().lower().strip()
               senha = form['senha'].value()
               usuario = auth.authenticate(
                    request,
                    username=login,
                    password=senha
               )
               if usuario is not None:
                    auth.login(request, usuario)
                    next = request.GET.get("next", None)
                    if next is not None:
                         return redirect(next)
                    return redirect('amazoncred:login')

            
          messages.error(request, "Login ou Senha incorretos")
          return render(request, 'pages/login/login-page.html', {'form': form})
     else:
          parametro = request.GET.get('parametro')
          formLogin = LoginForm()
          contexto = {
               'form': formLogin
          }
     template_name = 'partials/login/_login_partial.html' if parametro else 'pages/login/login-page.html'
               
     return render(request, template_name, contexto)

def pesquisar_post_htmx(request):
     termo_pesquisado = request.POST.get('q', '').strip()
     print(termo_pesquisado)
     if not termo_pesquisado:
          return render(request, 'partials/noticias/_list_posts_search.html')

     posts = Post.objects.filter( 
                    Q(titulo__icontains = termo_pesquisado)
                    ).order_by('-id')[:11]
     return render(request, 'partials/noticias/_list_posts_search.html', {'posts': posts })

def pesquisar_post(request):
     termo_pesquisado = request.POST.get('q', '').strip()
     print(termo_pesquisado)
     if not termo_pesquisado:
          return render(request, 'partials/noticias/_list_posts_search.html')

     posts = Post.objects.filter( 
                    Q(titulo__icontains = termo_pesquisado)
                    ).order_by('-id')[:11]
     
     return render(request, 'pages/noticias/blog.html', {'posts': posts })


def transparencia(request):
     return render(request, 'pages/transparencia/transparencia.html')

def tab(request):
     tipo = request.GET.get('tipo')
     relatorios = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
     contexto = {   'obj_list': relatorios,
                    'tipo': tipo
               }

     return render(request, 'pages/transparencia/partials/_lista_relatorios.html', contexto)


@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def novo_relatorio(request):
     
     if request.method == "POST":
          id = request.POST.get('id')
          tipo = request.POST.get('tipo')
          
          if id:
               relatorio = get_object_or_404(Relatorio, pk = id)
               form = RelatorioForm(request.POST, request.FILES, instance=relatorio)
               if form.is_valid():
                    form.save()
                    
          else:
               form = RelatorioForm(request.POST, request.FILES)
          
               if form.is_valid():
                    relatorio = form.save(commit=False)
                    relatorio.tipo_relatorio = tipo.upper()
                    relatorio.save()
          
          demonstracoes_contabeis = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
          
          return render(request, 'pages/transparencia/partials/_lista_relatorios.html',{'obj_list': demonstracoes_contabeis})
     else:
          tipo = request.GET.get('tipo')
          form = RelatorioForm()
          contexto = {'form': form,
                      'tipo': tipo,
                      'novo': True,
                    'titulo':'Novo Relatório' }
          return render(request, 'pages/transparencia/partials/_novo_relatorio.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def editar_relatorio(request):
     
     id = request.GET.get('id')
     relatorio = get_object_or_404(Relatorio, pk = id)
     form = RelatorioForm(instance=relatorio)
     contexto = {'form': form,
                    'tipo': relatorio.tipo_relatorio,
                    'id': id,
                    'titulo':'Editar Relatório'}
     return render(request, 'pages/transparencia/partials/_novo_relatorio.html', contexto)

@login_required(login_url="amazoncred:login", redirect_field_name="next")  
def remover_relatorio(request):
     
     id = request.POST.get('id')
     tipo = request.POST.get('tipo')

     print(id, tipo, '|\n' ,request.POST)
     
     relatorio = get_object_or_404(Relatorio, pk = id)
     relatorio.delete()
     
     demonstracoes_contabeis = Relatorio.objects.filter(tipo_relatorio = tipo.upper()).order_by('-id')
     
     return render(request, 'pages/transparencia/partials/_lista_relatorios.html',{'obj_list': demonstracoes_contabeis})

"""
class RecipeListViewTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(tags__slug=self.kwargs.get('slug', ''))
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(
            slug=self.kwargs.get('slug', '')
        ).first()

        if not page_title:
            page_title = 'No recipes found'

        page_title = f'{page_title} - Tag |'

        ctx.update({
            'page_title': page_title,
        })

        return ctx

"""

comunidadeativa/templates/pages/transparencia/partials/_lista_relatorios.html
{% if user.is_authenticated %}
<div class="d-flex justify-content-end">
    <div class="align-self-end mt-1"> 
      <button hx-get="{% url 'amazoncred:novo_relatorio' %}?tipo={{tipo}}" 
              hx-target="#tab-contents" class="btn btn-success"> Novo </button>
    </div>
</div>
{% endif %}
            

<div class="table-responsive">
    <table class="table table-striped">
        <colgroup>
            <col class="col-6">
            <col class="col-2">
        </colgroup>
        <thead>
            <tr>
              <th scope="col">Título</th>
              <th scope="col">Baixar</th>
              {% if user.is_authenticated %}
              <th scope="col">Editar</th>
              <th scope="col">Apagar</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for obj in obj_list  %}
            <tr>
              <td>{{ obj.titulo }}</td>
              {% if obj.arquivo %}
              
              <td><a href="{{obj.arquivo.url}}" target="_blank"><i class="fa-solid fa-download"></i></a></td>
              {% else %}
              <td>#</td>
              {% endif %}
              
              {% if user.is_authenticated %}
              <td> 
                <a href="#" hx-get="{% url 'amazoncred:editar_relatorio' %}?id={{obj.id}}" 
                hx-target="#tab-contents">
                  <i class="fa-solid fa-pen-to-square"></i>
                </a>
              </td>
              <td> <form action="" hx-POST="{% url 'amazoncred:remover_relatorio' %}"  
                hx-target="#tab-contents" _="on htmx:confirm(issueRequest)
                halt the event
                call Swal.fire({icon: 'error', title: 'Confirmar Exclusão', text:'Você deseja continuar?',showCancelButton: true,cancelButtonText:'Cancelar'})
                if result.isConfirmed issueRequest()"
                >
                  <input type="hidden" name="id", value="{{obj.id}}">
                  <input type="hidden" name="tipo" value="{{tipo}}">
                  <button style="border: none; color: var(--color-primary)" type="submit"><i class="fa-solid fa-trash"></i></button>
                  </form>
                </a> 
              </td>
              {% endif %}

            </tr>
            {% empty %}
            <tr><td>vazio</td></tr>
            {% endfor %}
          </tbody>
    </table>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

comunidadeativa/templates/pages/transparencia/partials/_novo_relatorio.html
{% load widget_tweaks %}

<h2>{{titulo}} </h2>

<form hx-post="{% url 'amazoncred:novo_relatorio' %}" 
      hx-target="#tab-contents" enctype="multipart/form-data">      
  {% csrf_token %}

  {% for field in form.visible_fields %}
  
    <div class="form-group mt-3 mb-3 d-flex row">
        <div class="label-class col-sm-2 text-start text-sm-end">
          <label class="col-form-label " for="{{ field.id_for_label}}">
            {{field.label}}</label>
          </div>
        <div class="col-sm-8">
          
          {{field|add_class:'form-control'}}
          
            

          {% if field.errors %}
            <span style="color: red;" role="alert">
                {{field.errors}}   
            </span>
            {% endif %}
          </div>
          <small class="form-text text-muted d-flex justify-content-center">{{ field.help_text }}</small>
        </div>
        {% endfor %}
      <input type="hidden" value="{{tipo}}" name='tipo'>
      <input type="hidden" value="{{id}}" name='id'>
    
      
      <div class="d-flex justify-content-end">
        <div class="align-self-end mt-1"> 
          <button class="btn btn-success">Enviar</button>
          <button class="btn btn-secondary" 
                  hx-get="{% url 'amazoncred:tab' %}?tipo={{tipo}}"
                  hx-trigger='click' 
                  hx-indicator="#indicator"
          
          
          >Cancelar</button>
      </div>
  </div>

</form>